<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;

class Sale extends BaseModel
{
    use HasFactory;

    protected $fillable = ['amount'];

    public static function rules()
    {
        return [
            'uuid' => 'required|uuid',
            'amount' => 'required'
        ];
    }

    public function beforeSave($model)
    {
        parent::beforeSave($model); // TODO: Change the autogenerated stub

        $model->uuid = \Str::uuid()->toString();
        $model->amount = 0; //depois será atualizado
    }

    public function products(): BelongsToMany
    {
        return $this->belongsToMany(Product::class)->withPivot('amount');
    }

    public function afterSave()
    {
    }
}
